apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cm-frontend-react
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kirapixel/cm-frontend-react.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: prd-cm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
