apiVersion: v1
kind: Secret
metadata:
  name: cm-frontend-react-secret
  namespace: prd-cm
type: Opaque
stringData:
  # Optional: use only if you need auth headers/certs via nginx customization later.
  DUMMY: "change-me"
